//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOC2018 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AOC2018.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###### Answers for: Day {0} ######.
        /// </summary>
        internal static string AnswersForDay {
            get {
                return ResourceManager.GetString("AnswersForDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a day to run or press any other key to run all days.
        /// </summary>
        internal static string ChoseADay {
            get {
                return ResourceManager.GetString("ChoseADay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find input file!.
        /// </summary>
        internal static string Could_not_find_input_file {
            get {
                return ResourceManager.GetString("Could_not_find_input_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not run Day{0}.
        /// </summary>
        internal static string Error_CouldNotRunDay {
            get {
                return ResourceManager.GetString("Error_CouldNotRunDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press [Enter] to exit.
        /// </summary>
        internal static string ExitNotice {
            get {
                return ResourceManager.GetString("ExitNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string Part_1_Response {
            get {
                return ResourceManager.GetString("Part_1_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string Part_2_Response {
            get {
                return ResourceManager.GetString("Part_2_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press [Enter] to exit.
        /// </summary>
        internal static string Program_Main_Press__Enter__to_exit {
            get {
                return ResourceManager.GetString("Program_Main_Press__Enter__to_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running all days.
        /// </summary>
        internal static string RunAllDays {
            get {
                return ResourceManager.GetString("RunAllDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advent of Code 2018.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
